### ISSUE TITLE
Improve the README document

### ISSUE THREAD

**Issue by gvegayon** [UofUEpiBio/epiworldpy#21]
The README document should resemble the existing one on `epiworldR`. As not all functions available in `epiworldR` have been ported here, this issue should be addressed by replicating as much as possible from the readme file, without having to add additional functions (that will be done later).

**Comment by IsaccBarker** [comment]
Blocked by #31, #33, #26, and others.

**Comment by IsaccBarker** [comment]
Unblocked; should have been sooner but #33 was holding me up despite already being done? Anyways, it appears some of the binding code for `GettingStarted.qml` has gone missing... I still have the graphs from when I showcased this (August 28 I want to say?) I'll work on tracking this down, but for now I assume we can use the old graphs.

<img width="1171" alt="Screenshot 2024-09-17 at 9 02 42 PM" src="https://github.com/user-attachments/assets/96efaf30-017e-4cfb-b4d2-62185f8ed108">
