### ISSUE TITLE
Fix sphinx website

### ISSUE THREAD

**Issue by gvegayon** [UofUEpiBio/epiworldpy#44]
Current state:

- Images from readme are missing.
- There's no menu.
- There doesn't seem to be any link to the docstring docs.

![Screenshot 2024-09-18 at 10 05 08 AM](https://github.com/user-attachments/assets/67f978c6-8afb-461b-81e9-2d1fd0048109)

**Comment by gvegayon** [comment]
We can discuss this during today's meeting.

**Comment by IsaccBarker** [comment]
See [this comment](https://github.com/UofUEpiBio/epiworldpy/pull/43#issuecomment-2357608219).

**Comment by IsaccBarker** [comment]
> There's no menu.

Would you mind clarifying? What menu are you expecting?

**Comment by IsaccBarker** [comment]
I tried assigning this to a milestone but it keeps not saving; I'll try again tomorrow assuming this is an error with GitHub.

@IsaccBarker
